# Деплой на GitHub Pages
name: Deploy to GitHub Pages  

on:
  release:
    # Запускается при создании релиза
    types: [published]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        # Получение кода из репозитория
      - name: Checkout code  
        uses: actions/checkout@v3
        
        # Создание папки с версиями
      - name: Create versioned folder
        run: |
          mkdir -p public/v${{ github.event.release.tag_name }}
          cp -r *.html ru/ en/ public/v${{ github.event.release.tag_name }}/
        
        # Публикация на GitHub Pages
      - name: Deploy to GitHub Pages  
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_public
          keep_files: true
